club_info = {
    'America': 'https://fbref.com/en/squads/18d3c3a3/America-Stats',
    'Atlas' : 'https://fbref.com/en/squads/7c76bc53/Atlas-Stats',
    'Atletico_DSL' : 'https://fbref.com/en/squads/5d274ee4/Atletico-Stats',
    'Cruz_Azul' : 'https://fbref.com/en/squads/632f1838/Cruz-Azul-Stats',
    'FC_Juarez' : 'https://fbref.com/en/squads/29bff345/FC-Juarez-Stats',
    'Guadalajara' : 'https://fbref.com/en/squads/c02b0f7a/Guadalajara-Stats',
    'Leon' : 'https://fbref.com/en/squads/fd7dad55/Leon-Stats',
    'Mazatlan' : 'https://fbref.com/en/squads/f0297c23/Mazatlan-Stats',
    'Monterrey' : 'https://fbref.com/en/squads/dd5ca9bd/Monterrey-Stats',
    'Necaxa' : 'https://fbref.com/en/squads/752db496/Necaxa-Stats',
    'Pachuca' : 'https://fbref.com/en/squads/1be8d2e3/Pachuca-Stats',
    'Puebla' : 'https://fbref.com/en/squads/73fd2313/Puebla-Stats',
    'Queretaro': 'https://fbref.com/en/squads/c3352ce7/Queretaro-Stats',
    'Santos' : 'https://fbref.com/en/squads/03b65ba9/Santos-Laguna-Stats',
    'Tijuana': 'https://fbref.com/en/squads/a42ddf2f/Tijuana-Stats',
    'Toluca': 'https://fbref.com/en/squads/44b88a4e/Toluca-Stats',
    'UANL' : 'https://fbref.com/en/squads/d9e1bd51/UANL-Stats',
    'UNAM' : 'https://fbref.com/en/squads/c9d59c6c/Pumas-UNAM-Stats',
    'Liga_MX' : 'https://fbref.com/en/comps/31/Liga-MX-Stats'
}